# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      packages: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Check version
        run: npm version

      - name: npm install
        run: |
          npm i

      - name: Running build
        run: |
          npm run build

      - name: Running tests
        run: |
          npm run test

      - name: Docs generation
        run: |
          npm run doc

      - name: Dist => Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist

      - name: coverage => Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage

      - name: docs => Artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs

      - name: GitHub Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "updated by github-actions [skip ci] "
          git push

      - uses: actions/setup-node@v2
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      # Publish to npm
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}