# This is a basic workflow that is manually triggered

name: Publish to NPM

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  npm_publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Git & NPM config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        npm config set save false

    - name: npm install
      run: |
        npm i
        git status
        git diff

    - name: Running build
      run: |
        npm run build

    - name: Running tests
      run: |
        npm run test

    - name: Docs generation
      run: |
        npm run doc

    - uses: actions/setup-node@v2
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    # Publish to npm
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}