# This is a basic workflow that is manually triggered

name: Publish New Version

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version_parameters:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'npm version parameters: [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease [--preid=<prerelease-id>]'
        # Default value if no value is explicitly provided
        default: 'patch'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Git & NPM config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        npm config set save false

    - name: npm install
      run: |
        npm i
        git status
        git diff

    - name: Version bump
      run: |
        npm version ${{ github.event.inputs.version_parameters }} -m "Version (${{ github.event.inputs.version_parameters }}): %s [skip ci]"
  
    - name: Running build
      run: |
        npm run build

    - name: Running tests
      run: |
        npm run test

    - name: Docs generation
      run: |
        npm run doc

    - name: Dist => Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          dist

    - name: coverage => Artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage

    - name: docs => Artifact
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs

    - name: GitHub Push
      run: |
        git add .
        git commit --amend -m "updated by github-actions [skip ci]"
        git push --tags origin master
        git push origin master

    - uses: actions/setup-node@v2
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    # Publish to npm
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}